CREATE TABLE "CARDS" (
                    "ID" INTEGER NOT NULL UNIQUE,
                    "CARDID" TEXT NOT NULL,
                    "CARDNAME" TEXT,
                    "CARDTEXT" TEXT,
                    "FLAVORTEXT" TEXT,
                    "ARTISTNAME" TEXT,
                    "TARGETING_ARROW_TEXT" TEXT,
                    "HOW_TO_EARN_GOLDEN" TEXT,
                    "HOW_TO_EARN" TEXT,
                    "HERO_POWER" TEXT,
                    "HEALTH" INT,
                    "CARD_SET" INT,
                    "CLASS" INT,
                    "FACTION" INT,
                    "CARDTYPE" INT,
                    "RARITY" INT,
                    "COST" INT,
                    "SPELL_SCHOOL" INT,
                    "ATK" INT,
                    "DURABILITY" INT,
                    "CARDRACE" INT,
                    "TAGS" TEXT,
                    PRIMARY KEY("ID" AUTOINCREMENT)
             );